name: SimpleNews
options:
  bundleIdPrefix: com.SimpleNews
targets:
  SimpleNews:
    type: application
    platform: iOS
    deploymentTarget: '13.0'
    dependencies:
      - package: SDWebImage
      - package: Lottie
    sources:
      - path: SimpleNews
    info:
      path: SimpleNews/Support/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: "48KF4TL849"
packages:
  SDWebImage:
   url: https://github.com/SDWebImage/SDWebImage
   from: 5.12.0
  Lottie:
   url: https://github.com/airbnb/lottie-ios
   from: 3.3.0
